language:
  - node_js

node_js:
  - '9'
  - '8'
  - '7'

services:
  - postgresql
  - redis-server

addons:
  postgresql: '9.4'

env:
  global:
    - NODE_ENV=test
    - export DATABASE_TEST_URL=postgresql://localhost/koa_api_test

before_script:
  - psql -c 'create database koa_api_test;' -U postgres

script:
  - npm run test
